search_place:
  fields:
    query:
      required: true
      example: "판교 스타벅스"
      selector:
        text:

get_directions:
  fields:
    origin:
      required: true
      example: person.me
      selector:
        entity:
    destination:
      required: true
      example: "{latitude: 37.3945, longitude: 127.1112}"
      selector:
        entity:
    waypoints:
      example: "[zone.office, {latitude: 37.39, longitude: 127.11}]"
      selector:
        object:
          multiple: true
    mode:
      default: car
      selector:
        select:
          options:
            - car
            - traffic
            - walk
            - bicycle
