search_place:
  fields:
    query:
      required: true
      example: "판교 스타벅스"
      selector:
        text:

search_nearby:
  fields:
    center:
      required: true
      example: "{latitude: 37.5665, longitude: 126.978}"
      selector:
        location:
          radius: false
    category:
      example: CE7
      selector:
        select:
          translation_key: category
          options:
            - MT1
            - CS2
            - PS3
            - SC4
            - AC5
            - PK6
            - OL7
            - SW8
            - BK9
            - CT1
            - AG2
            - PO3
            - AT4
            - AD5
            - FD6
            - CE7
            - HP8
            - PM9
    query:
      example: "스타벅스"
      selector:
        text:
    radius:
      default: 1000
      selector:
        number:
          min: 1
          max: 20000
          unit_of_measurement: m
          mode: box

get_directions:
  fields:
    origin:
      required: true
      example: "{latitude: 37.5665, longitude: 126.978}"
      selector:
        location:
          radius: false
    destination:
      required: true
      example: "{latitude: 37.3945, longitude: 127.1112}"
      selector:
        location:
          radius: false
    waypoints:
      example: "[zone.office, {latitude: 37.39, longitude: 127.11}]"
      selector:
        entity:
          multiple: true
    mode:
      default: car
      selector:
        select:
          translation_key: mode
          options:
            - car
            - traffic
            - walk
            - bicycle
